[package]
name = "v5ctl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive"] }
itertools = "0.13.0"
serde_json = "1.0.118"
socket2 = "0.5.7"
indicatif = "0.17.8"
tokio = { version = "1.38.0", features = ["net", "macros", "io-util", "rt", "full"] }
v5d-protocol = { version = "0.1.0", path = "../v5d-protocol" }
vex-v5-serial = "0.3.3"
rustyline = "14.0.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
