[package]
name = "v5d"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
ctrlc = { version = "3.4.4", features = ["termination"] }
log = "0.4.21"
serde_json = "1.0.118"
simplelog = "0.12.2"
tokio = { version = "1.38.0", features = ["net", "macros", "io-util"] }
v5d-interface = { version = "0.1.0", path = "../v5d-interface" }
vex_v5_serial = { git = "https://github.com/vexide/vex-v5-serial", version = "0.0.1" }
