[package]
name = "v5d"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive"] }
ctrlc = { version = "3.4.4", features = ["termination"] }
log = "0.4.21"
serde_json = "1.0.118"
snafu = { version = "0.8.9", features = ["rust_1_81"] }
tokio = { version = "1.47.1", features = ["net", "macros", "io-util"] }
tokio-util = "0.7.16"
tracing-subscriber = "0.3.20"
v5d-interface = { version = "0.1.0", path = "../v5d-interface" }
vex-v5-serial = "0.3.3"
